; ┬ ¤Єюь Їрщых ьюцэю шчьхэшЄ№ эрёЄЁющъш ъюьяшы ЄюЁр яю єьюыўрэш■.
J0			; эх фхырЄ№ эрўры№э√щ jump эр main() 
8			; юяЄшьшчрЎш  фы  Pentium II яЁюЎхёёюЁр.
r-			; чряЁхЄшЄ№ шчьхэхэшх фюёЄєяэющ ярь Єш т *.com Їрщырї
X			; чряЁхЄшЄ№ тъы■ўхэшх т т√їюфэющ Їрщы эрфяшёш SPHINXC--
oc			; юяЁшьшчрЎш  яю ЁрчьхЁє ъюфр
w			; т√фртрЄ№ яЁхфєяЁхцфхэш 
wf=warning.txt		; яЁхфєяЁхцфхэш  т√тюфшЄ№ т Їрщы warning
nw=1			; эх яюърч√трЄ№ ъюх-ъръшх ю°шсъш т warning.txt
nw=2			; эх яюърч√трЄ№ ъюх-ъръшх ю°шсъш т warning.txt
;de			; шёяюы№чютрЄ№ тЁхьхээюх Ёрё°шЁхэшх Єшяр яЁш фхыхэшш
;ON			; тъы■ўшЄ№ юяЄшьшчрЎш■ ўшёхы
;ost			; юяЄшьшчшЁютрЄ№ ЄхъёЄют√х ъюэёЄрэЄ√
IP=..\lib